@startuml

!include ../../common.puml

actor P
boundary VCH
control CH
entity ESP32

P -> VCH : solicitudCrearESP32()
activate VCH
VCH--> P : mostrarFormularioCrearESP32()
P -> VCH : CrearESP32(datos)
VCH-> CH : validarDatos(datos)
alt Formato Válido
    CH -> ESP32 : comprobarDuplicados(datos)
    alt No Duplicados
    ESP32 --> CH : noDuplicados()
    deactivate ESP32
        CH -> ESP32 : crearESP32(datos)
    activate ESP32
    ESP32 --> CH : confirmacionCreacion()
    deactivate ESP32
    CH --> VCH : confirmacionCreacion()
    deactivate CH
    VCH --> P : mostrarConfirmacionCreacion()
    else Duplicados
    ESP32 --> CH : duplicadosEncontrados()
    deactivate ESP32
    CH --> VCH : errorDuplicados()
    deactivate CH
    VCH --> P : mostrarErrorDuplicados()
    end
else Formato Inválido
    CH --> VCH : errorValidacion()
    deactivate CH
    VCH --> P : mostrarErrorValidacion()
end
@enduml