@startuml
!include ../../common.puml

actor P
boundary VCH
control CH
entity CESP32

P -> VCH : solicitudRenombrarESP32()
activate VCH
VCH --> P : mostrarFormularioRenombrarESP32()
P -> VCH : RenombrarESP32(datos)
VCH -> CH : validarDatos(datos)
alt Formato Válido
    CH -> CESP32 : comprobarDuplicados(datos)
    alt No Duplicados
        CESP32 --> CH : noDuplicados()
        deactivate CESP32
        CH -> CESP32 : renombrarESP32(datos)
        activate CESP32
        CESP32 --> CH : confirmacionRenombrado()
        deactivate CESP32
        CH --> VCH : confirmacionRenombrado()
        deactivate CH
        VCH --> P : mostrarConfirmacionRenombrado()
    else Duplicados
        CESP32 --> CH : duplicadosEncontrados()
        deactivate CESP32
        CH --> VCH : errorDuplicados()
        deactivate CH
        VCH --> P : mostrarErrorDuplicados()
    end
else Formato Inválido
    CH --> VCH : errorValidacion()
    deactivate CH
    VCH --> P : mostrarErrorValidacion()
end
@enduml