@startuml
title UC-043 renombrar luz

!include ../../common.puml


actor P
boundary VL
control CL
entity L 
P -> VL : Clic en "Renombrar Luz"
activate VL
VL -> P : mostrarFormularioRenombrarLuz()
P -> VL : Enviar datos de la luz a renombrar
VL -> CL : validarDatos(datos)
alt Formato Válido
    CL -> L : comprobarDuplicados(datos)
    alt No Duplicados
        L --> CL : noDuplicados()
        deactivate L
        CL -> L : renombrarLuz(datos)
        activate L
        L --> CL : confirmacionRenombrado()
        deactivate L
        CL -> VL : confirmacionRenombrado()
        deactivate CL
        VL -> P : mostrarConfirmacionRenombrado()
    else Duplicados
        L --> CL : duplicadosEncontrados()
        deactivate L
        CL -> VL : errorDuplicados()
        deactivate CL
        VL -> P : mostrarErrorDuplicados()
    end
else Formato Inválido
    CL -> VL : errorValidacion()
    deactivate CL
    VL -> P : mostrarErrorValidacion()
end
@enduml
