@startuml
skinparam classAttributeIconSize 0
hide empty members

package "Hardware" {

class "ESP32_control" as C_esp32_control {
  -setup()
  -loop()
  -callSupabaseRPC()
  -checkCalibrationRPC()
  -checkManualRecordRPC()
  -checkProgramRecordRPC()
  -activatePumpByGPIO()
  -markCalibrationAsCompleted()
  -markRecordAsCompleted()
  -registerExecution()
  -setMotor()
  -pwmWritePin()
  -brakeA()
  -brakeB()
  -pararCoast()
  -pararBrake()
  -checkLightProgramRPC()
  -setLight()
  -registerLightHistory()
}

}

@enduml
