@startuml
autonumber

actor "Propietario" as A
participant "CreateESP32 (React)" as UI
participant "Aplicacion (Logica Cliente)" as APP
participant "Supabase JS Client" as SB
database "PostgreSQL" as DB

A -> UI: iniciarCasoUso()
activate UI
UI -> APP: validarEntradaYContexto()
activate APP
alt validacion incorrecta
  APP --> UI: errorValidacion
  UI --> A: mostrarError()
else validacion correcta
  APP -> SB: auth.getSession()
  activate SB
  SB -> DB: query/rpc
  activate DB
  DB --> SB: datos/estado
  deactivate DB
  SB --> APP: respuesta
  deactivate SB
  APP -> SB: select('systems')
  activate SB
  SB -> DB: query/rpc
  activate DB
  DB --> SB: datos/estado
  deactivate DB
  SB --> APP: respuesta
  deactivate SB
  APP -> SB: select('admin_users')
  activate SB
  SB -> DB: query/rpc
  activate DB
  DB --> SB: datos/estado
  deactivate DB
  SB --> APP: respuesta
  deactivate SB
  APP -> SB: select('esp32')
  activate SB
  SB -> DB: query/rpc
  activate DB
  DB --> SB: datos/estado
  deactivate DB
  SB --> APP: respuesta
  deactivate SB
  APP -> SB: select('roles')
  activate SB
  SB -> DB: query/rpc
  activate DB
  DB --> SB: datos/estado
  deactivate DB
  SB --> APP: respuesta
  deactivate SB
  APP -> SB: insert('esp32')
  activate SB
  SB -> DB: query/rpc
  activate DB
  DB --> SB: datos/estado
  deactivate DB
  SB --> APP: respuesta
  deactivate SB
  APP --> UI: respuestaOK
  UI --> A: mostrarConfirmacion()
end
deactivate APP
deactivate UI
@enduml
